language: node_js
node_js:
  - '5'
services:
  - mongodb
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
script:
  - npm run test
after_script:
  - npm install coveralls && cat ./coverage/lcov.info | coveralls
before_install:
  - openssl aes-256-cbc -K $encrypted_02ebef9cfc9c_key -iv $encrypted_02ebef9cfc9c_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host bygis.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - tar -jcf judy.tar.bz2 *
  - scp judy.tar.bz2 bygis@bygis.com
  - ssh bygis@bygis.com 'tar -jxf judy.tar.bz2 -C ./judy'
